name: Deploy Docusaurus to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_S3_BUCKET_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
      AWS_DISTRIBUTION_PRODUCTION: ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Build Docusaurus site
        run: yarn build

      ## Deploy to S3, Invalidate Cloudfront Cache
      - name: Deploy to S3, Invalidate Cloudfront Cache
        uses: reggionick/s3-deploy@v4
        with:
          folder: build
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_S3_BUCKET_REGION }}
          dist-id: ${{ secrets.AWS_DISTRIBUTION_PRODUCTION }}
          invalidation: /*
          delete-removed: true
          # no-cache: true
          private: true
          files-to-include: '{.*/**,**}'